const TRADUCCIONES: Record<string, string> = {
  // Selecciones - Mundial
  "Spain": "España",
  "France": "Francia",
  "Germany": "Alemania",
  "England": "Inglaterra",
  "Portugal": "Portugal",
  "Argentina": "Argentina",
  "Brazil": "Brasil",
  "Belgium": "Bélgica",
  "Netherlands": "Países Bajos",
  "Italy": "Italia",
  "Croatia": "Croacia",
  "Morocco": "Marruecos",
  "Uruguay": "Uruguay",
  "Colombia": "Colombia",
  "Switzerland": "Suiza",
  "United States": "Estados Unidos",
  "Mexico": "México",
  "Japan": "Japón",
  "South Korea": "Corea del Sur",
  "Senegal": "Senegal",
  "Austria": "Austria",
  "Poland": "Polonia",
  "Denmark": "Dinamarca",
  "Sweden": "Suecia",
  "Norway": "Noruega",
  "Ecuador": "Ecuador",
  "Chile": "Chile",
  "Paraguay": "Paraguay",
  "Peru": "Perú",
  "Bolivia": "Bolivia",
  "Venezuela": "Venezuela",
  "Canada": "Canadá",
  "Australia": "Australia",
  "Egypt": "Egipto",
  "Nigeria": "Nigeria",
  "Ghana": "Ghana",
  "Algeria": "Argelia",
  "Tunisia": "Túnez",
  "Saudi Arabia": "Arabia Saudita",
  "Iran": "Irán",
  "Qatar": "Catar",
  "Turkey": "Turquía",
  "Serbia": "Serbia",
  "Ukraine": "Ucrania",
  "Wales": "Gales",
  "Scotland": "Escocia",
  "Ireland": "Irlanda",
  "Czech Republic": "República Checa",
  "Greece": "Grecia",
  "Romania": "Rumania",
  "Hungary": "Hungría",
  "Finland": "Finlandia",
  "Iceland": "Islandia",
  "New Zealand": "Nueva Zelanda",
  "Costa Rica": "Costa Rica",
  "Jamaica": "Jamaica",
  "Panama": "Panamá",
  "Jordan": "Jordania",
  "Uzbekistan": "Uzbekistán",
  "Cape Verde Islands": "Cabo Verde",
  "DR Congo": "RD Congo",
  "Congo DR": "RD Congo",
};

export function traducirEquipo(nombre: string): string {
  return TRADUCCIONES[nombre] || nombre;
}